[workspace]

default-members = [
#    "projects/voml-ast",
    "projects/voml-parser",
#    "projects/arc-fmt",
#    "projects/voml-vm",
#    "projects/voml-from",
]
members = ["projects/*"]

[profile.release]
lto = true
opt-level = "s"
