[workspace]

default-members = [
    "projects/arc-ast",
    "projects/arc-pest",
    "projects/arc-fmt",
    "projects/arc-number",
]
members = ["projects/*"]

[profile.release]
lto = true
opt-level = "s"
