[workspace]

default-members = [
#    "projects/voml-ast",
    "projects/voml-ast",
#    "projects/arc-fmt",
    "projects/voml-types",
#    "projects/voml-from",
]
members = [
    "projects/*"
]

[profile.release]
lto = true
opt-level = "s"
