[workspace]

default-members = [
#    "projects/voml-ast",
    "projects/voml-ast",
#    "projects/arc-fmt",
    "projects/voml-error",
#    "projects/voml-from",
]
members = ["projects/*"]

[profile.release]
lto = true
opt-level = "s"
